sudo: required

services:
  - docker

language: python

addons:
  sonarcloud:
    organization: "marialujan019"
    token:
      secure: "20f8ea3d855f36f36ad152b8d198efe5c4fc300b"

script:
  - python -m pytest -v
  - sonar-scanner

notifications:
  slack: 
    rooms:
      - cicd-tpsw:vkPhz7xu320ldwwbKU7TJ6B9
    on_success: always 
    on_failure: always 

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "main" && sh .travis/deploy_heroku.sh