sudo: required

services:
  - docker

language: python

addons:
  sonarcloud:
    organization: "marialujan019"
    token:
      secure: 9b57348a857aae8e0d67c0726549199e08ef2595

script:
  - python -m pytest -v
  - sonar-scanner

notifications:
  slack: 
    rooms:
      - cicd-tpsw:vkPhz7xu320ldwwbKU7TJ6B9
    on_success: always 
    on_failure: always 

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "main" && sh .travis/deploy_heroku.sh